version: '2'
services:
  app:
    build: ./mongoAPI
    command: python -u main.py
      - /bin/bash
      - -c
      - |
        ls -l
        pwd
        cd mongoAPI
        pwd
        ls -l
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongoAPI/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
  vue:
     build: ./demo_1
     ports:
      - 8900:8900
  

